### ISSUE TITLE
Error MovingLight

### ISSUE THREAD

**Issue by fruechtegott** [segfault16/audio-reactive-led-strip#37]
<img width="713" alt="bildschirmfoto 2019-01-03 um 23 45 52" src="https://user-images.githubusercontent.com/18394044/50665687-ec52fb00-0fb1-11e9-9b9d-86d904d30974.png">
Seemed like Issue #35 but its not. After the error occurs LEDs index 149 and 150 are the only ones active and server needs to be restarted, which is annoying.

**Comment by segfault16** [comment]
Thought I resolved this issue already in https://github.com/segfault16/audio-reactive-led-strip/commit/402c1a5c0ea1217df1494e8228d5974500fde62a.
Which revision?

**Comment by segfault16** [comment]
Has been fixed. If the bug still persists, please open a new issue.
