### ISSUE TITLE
Pendulum lightflip fader

### ISSUE THREAD

**Issue by fruechtegott** [segfault16/audio-reactive-led-strip#58]
Fader does not work as intended. 
`# default, min, max, stepsize`
`("lightflip", [1, -1, 1, 2])`
Starts at 1. When moved, jumps to 0, then up to 2.
Looks like no negative values are allowed in the new webUI?

**Comment by segfault16** [comment]
@fruechtegott Could be. Maybe your value is boolean?

**Comment by segfault16** [comment]
@segfault16 🤨

**Comment by fruechtegott** [comment]
Does not look boolean to me.
```
        if self.heightactivator is True:
            configArray = np.array([[self.lightflip * math.cos(2 * self._t)], [self.lightflip * math.cos(2 * self._t)],
                                    [self.lightflip * math.cos(2 * self._t)]])
```

**Comment by segfault16** [comment]
With `("lightflip", [1, -1, 1, 2])` you have two options: -1, 1.
This is a binary decision, is it not?
Btw: If you set it to `("lightflip", [1, -1, 1, 1])` all works fine.
Suggestion: Either convert setting to boolean or adjust stepsize if intermediate values between -1 and 1 make sense.

**Comment by segfault16** [comment]
Implemented as boolean by @fruechtegott
