### ISSUE TITLE
Store and load projects

### ISSUE THREAD

**Issue by fruechtegott** [segfault16/audio-reactive-led-strip#59]
After the 'projects'-merge we need a function for saving the keyboard setup and an easy way to change the default keyboard would also be nice.
If someone comes up with a better name for 'keyboard setup' you are very welcome.

**Comment by segfault16** [comment]
'keyboard setup' = project
Just like we have an option to store and load single configurations, we need to be able to store the keyboard layout including the configurations for slots in a 'project file' that can be exchanged.
